In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns
sns.set()

In [4]:
df = pd.read_csv('/Users/andreatitton/unox/unox_sample.csv')

In [12]:
df['datetime'] = df['datetime'].apply(lambda x: pd.Timestamp(x))

In [32]:
df

,CHAMBER TEMPERATURE,PROBE TEMPERATURE,SET TEMPERATURE,FAN SPEED,SET HUMIDITY,CHAMBER HUMIDITY,ALGORITHM SET TEMPERATURE,ALGORITHM SET HUMIDITY,ALGORITHM SET FAN,kind_of_cooking,program_name,alarm,test
datetime,,,,,,,,,,,,,
2018-05-07 05:32:30,38,33,99.5,1.0,100.0,0.0,99.5,100.0,2.0,2.0,NaN,NaN,1
2018-05-07 05:33:00,50,46,99.5,1.0,100.0,100.0,99.5,100.0,2.0,2.0,NaN,NaN,1
2018-05-07 05:33:30,66,61,99.5,1.0,100.0,100.0,99.5,100.0,2.0,2.0,NaN,NaN,1
2018-05-07 05:34:00,84,81,99.5,1.0,100.0,100.0,99.5,100.0,2.0,2.0,NaN,NaN,1
2018-05-07 05:34:30,97,99,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:35:00,108,114,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:35:30,110,120,99.5,1.0,100.0,80.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:36:00,110,120,99.5,1.0,100.0,70.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:36:30,107,116,99.5,1.0,100.0,80.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:37:00,104,112,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:37:30,102,107,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:38:00,100,104,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:38:30,98,101,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:39:00,97,100,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:39:30,96,98,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:40:00,98,103,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:40:30,106,114,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:41:00,113,119,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:41:30,114,120,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:42:00,114,118,99.5,1.0,100.0,100.0,99.5,100.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:42:30,116,118,166.5,1.0,0.0,100.0,166.5,30.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:43:00,131,129,166.5,1.0,0.0,100.0,166.5,30.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:43:30,149,147,166.5,1.0,0.0,100.0,166.5,30.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:44:00,168,169,166.5,1.0,0.0,100.0,166.5,30.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:44:30,177,184,166.5,1.0,0.0,100.0,166.5,30.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:45:00,177,186,166.5,1.0,0.0,100.0,166.5,30.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:45:30,168,174,166.5,1.0,0.0,0.0,166.5,30.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:46:00,163,161,166.5,1.0,0.0,0.0,166.5,30.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:46:30,168,163,166.5,1.0,0.0,0.0,166.5,30.0,1.0,2.0,NaN,NaN,1
2018-05-07 05:47:00,171,167,166.5,1.0,0.0,0.0,166.5,30.0,1.0,2.0,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-06-18 23:01:00,174,178,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:01:30,171,174,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:02:00,168,170,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:02:30,175,175,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:03:00,175,178,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:03:30,175,180,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:04:00,173,177,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:04:30,170,174,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:05:00,170,172,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:05:30,176,177,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:06:00,175,178,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:06:30,171,175,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:07:00,168,172,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:07:30,175,177,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:08:00,177,183,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:08:30,175,180,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:09:00,173,178,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:09:30,170,174,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:10:00,169,171,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:10:30,174,176,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:11:00,175,180,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:11:30,175,180,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:12:00,173,177,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:12:30,170,174,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:13:00,169,172,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:13:30,174,173,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:14:00,176,178,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:14:30,173,178,171.5,4.0,90.0,65.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:15:00,171,175,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1
2018-06-18 23:15:30,169,172,171.5,4.0,90.0,78.0,171.5,90.0,4.0,2.0,NaN,NaN,1

In [14]:
df = df.set_index('datetime')